version: 2.1

orbs:
  unity: game-ci/unity@1.7.0

jobs:
  runner-test:
    machine: true
    resource_class: owaowa/test
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  test-unity-project:
    jobs:
      # - unity/create-activation-file:
      #     editor_version: "2022.1.11f1"

      # Ubuntu/Test-Windows-Mono
      # - unity/test:
      #     executor:
      #       name: unity/ubuntu
      #       editor_version: 2023.1.13f1
      #       target_platform: windows-mono
      #       resource_class: large
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     test-platform: 'playmode'
      #     context: unity
      #     name: test-windows

      # # Windows-IL2CPP
      # - unity/build:
      #     build-method: 'BuildCommand.PerformBuild'
      #     executor:
      #       name: unity/windows-2019
      #       editor_version: 2022.1.11f1
      #       target_platform: windows-il2cpp
      #       size: large
      #     step-name: Build Windows IL2CPP
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-il2cpp
      
      # # Windows-Runner-IL2CPP
      # - unity/build:
      #     build-method: 'BuildCommand.PerformBuild'
      #     executor:
      #       name: unity/windows-runner
      #       editor_version: 2022.1.11f1
      #       target_platform: windows-il2cpp
      #       resource_class: owaowa/test
      #     step-name: Build Windows IL2CPP
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-il2cpp

      # # Ubuntu Window-Mono
      # - unity/build:
      #     executor:
      #       name: unity/ubuntu
      #       editor_version: 2023.1.13f1
      #       target_platform: windows-mono
      #       resource_class: large
      #     step-name: Build Windows Mono
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-mono

      # Ubuntu Android
      - unity/build:
          build-method: 'BuildCommand.PerformBuild'
          executor:
            name: unity/ubuntu
            editor_version: 2023.1.13f1
            target_platform: android
            resource_class: large
          step-name: Build Android
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          build-target: Android
          compress: true
          context: unity
          name: build-Android-ubuntu
