version: 2.1

orbs:
  unity: game-ci/unity@1.7.0
  windows: circleci/windows@5.0.0
  docker: circleci/docker@2.4.0

jobs:
  runner-test:
    machine: true
    resource_class: owaowa/test
    steps:
      - run: echo "Hi I'm on Runners!"
  testjob:
    executor:
      name: windows/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:ad:8c:c9:4c:3e:31:35:3e:85:50:18:23:8d:50:d5"
      - checkout
      - run: echo "Ha Ha!"

  # Ubuntu Android Build 2
  build-android-ubuntu:
        docker:
          - image: unityci/editor:ubuntu-2023.1.13f1-android-3.0.1
        # executor:
        #   name: unity/ubuntu
        #   editor_version: 2023.1.13f1
        #   resource_class: large
        #   target_platform: android
        steps:
          - setup_remote_docker
          - checkout
          - unity/prepare-env:
              cache-version: v2.1
          - unity/build:
              build-target: Android
              compress: true
              cache-version: v2.1
              build-method: 'MyWorldBuildCommand.CustomBuildAndroid'
              # project-path: "."
              # build-method: 'GameCIBuildCommand.PerformBuild'
          - store_artifacts:
              path: Builds/Android
              destination: builds
          - unity/return-license
    
  # Window Android Build 2
  build-android-window:
        # vm_services:
        #   providers:
        #     ec2:
        #       windowsAMI: "unityci/editor:windows-2023.1.13f1-android-3.0.1"
        # executor:
        #   name: windows/default
        docker:
            - image: cimg/base:2024.01
          # - image: unityci/editor:ubuntu-2023.1.13f1-android-3.0.1
        # machine: 
        #   image: ubuntu-2204:current
        # executor:
        #   name: unity/windows-2022
        #   editor_version: 2023.1.13f1
        #   size: large
        #   target_platform: android
        steps:
          - add_ssh_keys:
              fingerprints:
                - "c1:1e:1c:e0:f6:68:6a:38:42:a3:88:bd:41:53:4a:d1"
          - checkout
          # - docker/pull:
          #     images: unityci/editor:ubuntu-2023.1.13f1-android-3.0.1
          # - run:
          #     name: check docker
          #     command: docker version
          # - run:
          #     name: "docker setup"
          #     command: |
          #       docker pull unityci/editor:windows-2023.1.13f1-android-3.0.1
          #       docker run -it unityci/editor:windows-2023.1.13f1-android-3.0.1 cmd.exe
          #     timeout: 1h
          - setup_remote_docker
          - unity/prepare-env:
              cache-version: v2.3.2
          # # # - unity/test:
          # # #     test-platform: "playmode"
          - unity/build:
              build-target: Android
              compress: true
              cache-version: v2.3.2
              # build-method: 'MyWorldBuildCommand.CustomBuildAndroid'
          #     project-path: "."
          #     build-method: 'GameCIBuildCommand.PerformBuild'
          # - store_artifacts:
          #     path: Builds/Android
          #     destination: builds
          - unity/return-license
  
  # Window Build 2
  build-window-il2cpp:
        # docker:
        #   - image: unityci/editor-windows-2023.1.13f1-windows-il2cpp-3.0.1
        executor:
          name: unity/windows-2019
          editor_version: 2023.1.13f1
          size: large
          target_platform: windows-il2cpp
        steps:
          # - setup_remote_docker
          - add_ssh_keys:
              fingerprints:
                - "c1:1e:1c:e0:f6:68:6a:38:42:a3:88:bd:41:53:4a:d1"
          - checkout
          - unity/prepare-env:
              cache-version: v2.win
          - unity/build:
              build-target: StandaloneWindows64
              compress: true
              cache-version: v2.win
              # build-method: 'MyWorldBuildCommand.CustomBuildWindows'
              # project-path: "."
              # build-method: 'GameCIBuildCommand.PerformBuild'
          - store_artifacts:
              path: Builds/Android
              destination: builds
          - unity/return-license

  # create-unity-activation-file:
  #       executor:
  #         name: unity/ubuntu
  #         editor_version: 2023.1.13f1
  #         target_platform: android
  #       steps:
  #         - unity/create-activation-file:
  #             editor_version: "2022.1.11f1"    

workflows:
  # create-activation:
  #   jobs:
  #     - unity/create-activation-file
  #         # editor_version: 2022.1.11f1

  # build-android:
  #   jobs:
  #     - build-android-ubuntu:
  #         context: unity
  
      # - build-android-window:
      #     context: unity

  # build-android-2:
  #   jobs:
  #     - build-android-window:
  #         context: unity
  
  build-windows:
    jobs:
      - build-window-il2cpp:
          context: unity