version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      
      # Activate Unity license (if needed)
      # Uncomment and replace placeholders with your license information
      # - run:
      #     name: Activate Unity License
      #     command: UnityHub activate -username <YOUR_USERNAME> -password <YOUR_PASSWORD>

      # Run Unity build
      - run:
          name: Unity Build
          command: Unity -quit -batchmode -logFile -projectPath "/root/project/." -executeMethod "MyWorldBuildCommand.CustomBuildAndroid"

workflows:
  version: 2
  build:
    jobs:
      - build
