version: 2.1

orbs:
  unity: game-ci/unity@1.7.0
  windows: circleci/windows@2.2.0

jobs:
  runner-test:
    machine: true
    resource_class: owaowa/test
    steps:
      - run: echo "Hi I'm on Runners!"
  testjob:
    executor:
      name: windows/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:ad:8c:c9:4c:3e:31:35:3e:85:50:18:23:8d:50:d5"
      - checkout
      - run: echo "Ha Ha!"

  # Ubuntu Android Build 2
  build-android-ubuntu:
        executor:
          name: unity/ubuntu
          editor_version: 2023.1.13f1
          resource_class: large
          target_platform: android
        steps:
          # - add_ssh_keys:
          #     fingerprints:
          #       - "70:ad:8c:c9:4c:3e:31:35:3e:85:50:18:23:8d:50:d5"
          - checkout
          - unity/prepare-env
          - unity/build:
              build-target: Android
              compress: true
              build-method: 'MyWorldBuildCommand.BuildAndroidDevelopment'
              # build-method: 'GameCIBuildCommand.PerformBuild'
          - unity/return-license

workflows:
  create-unity-activation-files:
    jobs:
      - unity/create-activation-file:
          editor_version: "2022.1.11f1"
  
  build:
    jobs:
      - build-android-ubuntu:
          context: unity
      requires:
        - create-unity-activation-files

      # Ubuntu/Test-Windows-Mono
      # - unity/test:
      #     executor:
      #       name: unity/ubuntu
      #       editor_version: 2023.1.13f1
      #       target_platform: windows-mono
      #       resource_class: large
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     test-platform: 'playmode'
      #     context: unity
      #     name: test-windows

      # # Windows-IL2CPP
      # - unity/build:
      #     build-method: 'BuildCommand.PerformBuild'
      #     executor:
      #       name: unity/windows-2019
      #       editor_version: 2022.1.11f1
      #       target_platform: windows-il2cpp
      #       size: large
      #     step-name: Build Windows IL2CPP
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-il2cpp
      
      # # Windows-Runner-IL2CPP
      # - unity/build:
      #     build-method: 'BuildCommand.PerformBuild'
      #     executor:
      #       name: unity/windows-runner
      #       editor_version: 2022.1.11f1
      #       target_platform: windows-il2cpp
      #       resource_class: owaowa/test
      #     step-name: Build Windows IL2CPP
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-il2cpp

      # # Ubuntu Window-Mono
      # - unity/build:
      #     executor:
      #       name: unity/ubuntu
      #       editor_version: 2023.1.13f1
      #       target_platform: windows-mono
      #       resource_class: large
      #     step-name: Build Windows Mono
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: StandaloneWindows64
      #     compress: true
      #     context: unity
      #     name: build-Windows-mono

      # Ubuntu Android
      # - unity/build:
      #     build-method: 'BuildCommand.PerformBuild'
      #     executor:
      #       name: unity/ubuntu
      #       editor_version: 2023.1.13f1
      #       target_platform: android
      #       resource_class: large
      #     step-name: Build Android
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     build-target: Android
      #     compress: true
      #     context: unity
      #     name: build-Android-ubuntu
